chore: push base image to registry; update smoke tests to pull images
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

diff --git a/.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi9.yaml b/.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi9.yaml
--- a/.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi9.yaml
+++ b/.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi9.yaml
@@ -12,11 +12,12 @@
 
 name: Empty workspace smoke test on udi9
 on:
-  pull_request:
-    paths-ignore:
-      - '**/*.md'
-      - .devfile.yaml
-      - LICENSE
+  workflow_run:
+    workflows: ["Pull Request Check"]
+    types:
+      - completed
+    branches:
+      - '**'
 
 env:
   # Use repository variable if set, otherwise fallback to default registry
@@ -28,6 +29,7 @@ env:
 
 jobs:
   workspace-api-tests-on-minikube:
+    if: github.event.workflow_run.conclusion == 'success'
     strategy:
       fail-fast: false
       matrix:
@@ -40,11 +42,17 @@ jobs:
     - name: Free runner space
       run: |
         sudo rm -rf /usr/local/lib/android
-      # obtain the PR number for tagging the image
     - name: Get PR number
       id: get_pr_number
       run: |
-        pr_number=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+        pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
+        if [ -z "$pr_number" ] || [ "$pr_number" == "null" ]; then
+          pr_number=$(echo "${{ github.event.workflow_run.head_branch }}" | grep -oE '[0-9]+' | head -1 || echo "")
+        fi
+        if [ -z "$pr_number" ]; then
+          echo "Error: Could not extract PR number from workflow_run event"
+          exit 1
+        fi
         echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
         echo ">>>>>>>>>>>$pr_number"
 
@@ -67,18 +75,18 @@ jobs:
         install minikube-linux-${{env.arch}} /usr/local/bin/minikube && rm minikube-linux-${{env.arch}}
         minikube start --vm-driver=docker --addons=ingress --cpus 2 --memory 6500
 
-    # connect with docker daemon in the minikube and build an image there
-    # we need to build the image in the minikube because we have just 14 GB of space on the runner
-    # the UBI have more than 9 GB size this approach saves the disk space
-    - name: Build base image
-      run: |
-        eval $(minikube docker-env)
-        cd base/ubi9 && docker build -t ${{ env.REGISTRY }}/base-developer-image:ubi9-latest .
+    - name: Login to Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ${{ env.REGISTRY }}
+        username: ${{ secrets.QUAY_USERNAME }}
+        password: ${{ secrets.QUAY_PASSWORD }}
 
-    - name: Build universal image
+    - name: Pull UDI image into minikube
       run: |
         eval $(minikube docker-env)
-        cd universal/ubi9 && docker build -t ${{ env.REGISTRY }}/universal-developer-image:ubi9-pr-${{ env.PR_NUMBER }} .
+        docker pull ${{ env.REGISTRY }}/universal-developer-image:${{env.arch}}-pr-${{ env.PR_NUMBER }}
+        docker tag ${{ env.REGISTRY }}/universal-developer-image:${{env.arch}}-pr-${{ env.PR_NUMBER }} ${{ env.REGISTRY }}/universal-developer-image:ubi9-pr-${{ env.PR_NUMBER }}
 
     - name: Checkout DWO
       uses: actions/checkout@master
@@ -105,8 +113,6 @@ jobs:
 
     - name: Check that UDI is present in the image list
       run: |
-        # we used it for the build above and do not need it anymore. It saves the disk space
-        minikube image rm ${{ env.REGISTRY }}/base-developer-image:ubi9-latest
         minikube image list --format table
 
     - name: Install NodeJs
